    This dataset provides a detailed representation of factors that influence student attendance in a college environment. It includes a wide variety of variables covering student demographics, lifestyle habits, academic background, environmental conditions, and attendance outcomes.
    Each record represents a unique student-day profile with realistic behavior patterns. Variables such as study hours, sleep duration, travel time, internet access, weather conditions, hostel residency, and type of class (online/offline) offer an in-depth view of how different factors collectively impact attendance consistency.
    The dataset reflects common real-world trends observed in educational institutions. For instance:
Students with higher study hours tend to show greater consistency in attendance. Rainy weather or long travel times negatively affect attendance. Online classes increase attendance likelihood due to convenience. Hostel students generally have lower travel time and slightly better attendance rates.
    Additionally, absence reasons are included to help understand common causes of absenteeism, such as illness, personal work, festivals, travel, or academic project commitments.
    The dataset is suitable for educational analysis, institutional planning, behavioral insights, research, dashboards, attendance trend visualization, and general statistical exploration. Since the data is fully synthetic, it avoids privacy issues while maintaining realistic patterns.

    source : kaggle;

In [12]:
import pandas as pd 

data = pd.read_csv("./Attendance_Prediction.csv")
data.head(5)

,student_id,age,gender,course,year,parent_education,internet_access,hostel_resident,class_type,weather,study_hours,sleep_hours,travel_time_minutes,attendance,absence_reason
0,200.99,17,male,pharmacy,1st year,high school,no,yes,offline,sunny,3.63,7.24,31,1,none
1,200.99,23,other,diploma,2nd year,high school,yes,yes,offline,cloudy,4.39,7.98,50,0,no reason
2,200.99,22,male,b.sc,3rd year,no formal,yes,yes,online,rainy,5.43,6.53,62,1,none
3,200.99,20,other,pharmacy,2nd year,no formal,yes,yes,offline,cloudy,0.21,7.11,63,0,personal work
4,200.99,20,female,pharmacy,1st year,no formal,yes,yes,online,sunny,1.77,9.35,81,0,project work

In [13]:
data.shape

(20000, 15)

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   student_id           20000 non-null  float64
 1   age                  20000 non-null  int64
 2   gender               20000 non-null  object
 3   course               20000 non-null  object
 4   year                 20000 non-null  object
 5   parent_education     20000 non-null  object
 6   internet_access      20000 non-null  object
 7   hostel_resident      20000 non-null  object
 8   class_type           20000 non-null  object
 9   weather              20000 non-null  object
 10  study_hours          20000 non-null  float64
 11  sleep_hours          20000 non-null  float64
 12  travel_time_minutes  20000 non-null  int64
 13  attendance           20000 non-null  int64
 14  absence_reason       20000 non-null  object
dtypes: float64(3), int64(3), object(9)
memory usage: 2.3+ MB

In [15]:
data.isnull().sum()

student_id             0
age                    0
gender                 0
course                 0
year                   0
parent_education       0
internet_access        0
hostel_resident        0
class_type             0
weather                0
study_hours            0
sleep_hours            0
travel_time_minutes    0
attendance             0
absence_reason         0
dtype: int64

In [16]:
data.columns

Index(['student_id', 'age', 'gender', 'course', 'year', 'parent_education',
       'internet_access', 'hostel_resident', 'class_type', 'weather',
       'study_hours', 'sleep_hours', 'travel_time_minutes', 'attendance',
       'absence_reason'],
      dtype='object')

In [17]:
#identification des variables qualitatives pour savoir le nombre de modalités par variable:

qualitative_cols = data.select_dtypes(include=['object', 'category']).columns
qualitative_cols

Index(['gender', 'course', 'year', 'parent_education', 'internet_access',
       'hostel_resident', 'class_type', 'weather', 'absence_reason'],
      dtype='object')

In [18]:
for col in qualitative_cols:
    nombre_modalites = data[col].nunique()
    print(f"- {col}  : {nombre_modalites} modalités")

- gender  : 3 modalités
- course  : 9 modalités
- year  : 4 modalités
- parent_education  : 5 modalités
- internet_access  : 2 modalités
- hostel_resident  : 2 modalités
- class_type  : 2 modalités
- weather  : 5 modalités
- absence_reason  : 7 modalités

In [19]:
#voir si la supprission des individus avec 'gender = other' va impacter le dataset:
nombre_individus_other = data[data['gender'] == 'other'].shape[0]
nombre_individus_other

6726

In [20]:
#supprimer les colonnes avec deux modalités (d'apres le tp , on doit avoir les variables avec au plus deux modalités)
colonnes_a_supprimer = ['student_id' , 'class_type', 'hostel_resident', 'internet_access']
data = data.drop(columns=colonnes_a_supprimer, axis=1)

In [21]:
#ajouter un id
data['id'] = data.index
cols = ['id'] + [col for col in data.columns if col != 'id']
df_processed = data[cols]
df_processed.head()

,id,age,gender,course,year,parent_education,weather,study_hours,sleep_hours,travel_time_minutes,attendance,absence_reason
0,0,17,male,pharmacy,1st year,high school,sunny,3.63,7.24,31,1,none
1,1,23,other,diploma,2nd year,high school,cloudy,4.39,7.98,50,0,no reason
2,2,22,male,b.sc,3rd year,no formal,rainy,5.43,6.53,62,1,none
3,3,20,other,pharmacy,2nd year,no formal,cloudy,0.21,7.11,63,0,personal work
4,4,20,female,pharmacy,1st year,no formal,sunny,1.77,9.35,81,0,project work

In [22]:
#supprimer les individus avec gender = other
df_filtered = df_processed[data['gender'] != 'other']
df_filtered.shape

(13274, 12)

In [23]:
#sauvegarder
new_file_name = 'dataset_apres_modification.csv'
df_filtered.to_csv(new_file_name, index=False)